---
# System requirements
- name: Install required system packages
  apt: pkg={{ item  }} state=installed update-cache=yes
  with_items:
    - build-essential
    - git-core
    - sqlite3
    - libffi-dev
    - libssl-dev
    - python-dev
    - python-virtualenv
    - python-pip

# Group and user
- name: Create the service group
  group: name={{ openbazaar_group }} state=present

- name: Create the service User
  user:
    name={{ openbazaar_user }}
    home={{ openbazaar_user_home_directory }}
    groups="{{ openbazaar_group }}"
    shell=/bin/bash
    system=yes

# Get the source and install app requirements
- name: check openbazaar downloaded
  stat: path={{ openbazaar_user_home_directory }}/openbazaar
  register: openbazaar_download

- name: Download OpenBazaar
  git:
    repo={{ openbazaar_git_url }}
    dest={{ openbazaar_user_home_directory }}/openbazaar
    version={{ openbazaar_git_version }}
  when: openbazaar_download.stat.exists == False

- name: Install Requirements
  pip:
    requirements={{ openbazaar_user_home_directory }}/openbazaar/requirements.txt
    virtualenv={{ openbazaar_user_home_directory }}/openbazaar/venv
    state=present

- name: Set git directory ownership
  file:
    path={{ openbazaar_user_home_directory }}/openbazaar
    state=directory
    recurse=true
    owner={{ openbazaar_user }}
    group={{ openbazaar_group }}

# Firewalling
- name: Install ufw
  apt: name=ufw

- name: Allow DHT through UFW
  ufw: proto=udp port={{ openbazaar_dht_port }} rule=allow

- name: Include Server tasks
  include: tasks/server.yml
  when: openbazaar_seed == false

- name: Include Seed tasks
  include: tasks/seed.yml
  when: openbazaar_seed == true

- name: Include SSL tasks
  include: tasks/ssl.yml
  when: openbazaar_ssl_enabled == true
