---

- name: Allow REST through UFW
  ufw: proto=tcp port={{ openbazaar_rest_port }} rule=allow
- name: Allow WebSockets through UFW
  ufw: proto=tcp port={{ openbazaar_websocket_port }} rule=allow
- name: Allow Heartbeat through UFW
  ufw: proto=tcp port={{ openbazaar_heartbeat_port }} rule=allow

- name: Install Config
  template:
    src=ob.cfg.j2
    dest={{ openbazaar_user_home_directory }}/ob.cfg
    owner={{ openbazaar_user }}
    group={{ openbazaar_group }}
    mode=0644
    force=yes
  notify:
    - restart server

- name: Install upstart script
  template:
    src=server/openbazaar_upstart.conf.j2
    dest=/etc/init/openbazaard.conf
    owner={{ openbazaar_user }}
    group={{ openbazaar_group }}
    mode=0644

- name: Start Server - Upstart
  service: name=openbazaard state=started
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int <= 14.04

- name: Install systemd script
  template:
    src=server/openbazaar_systemd.service.j2
    dest=/etc/systemd/system/openbazaard.service
    owner={{ openbazaar_user }}
    group={{ openbazaar_group }}
    mode=0644
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int > 14.04

- name: Start Server - Systemd
  systemd:
    state: restarted
    daemon_reload: yes
    name: openbazaard
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int > 14.04

